# GoReleaser configuration for Samuel
# Documentation: https://goreleaser.com

version: 2

project_name: samuel

before:
  hooks:
    - go mod tidy

builds:
  - id: samuel
    main: ./cmd/samuel
    binary: samuel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/ar4mirez/samuel/internal/commands.Version={{.Version}}
      - -X github.com/ar4mirez/samuel/internal/commands.Commit={{.Commit}}
      - -X github.com/ar4mirez/samuel/internal/commands.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^feat'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix'
      order: 1
    - title: 'Performance'
      regexp: '^perf'
      order: 2
    - title: 'Refactoring'
      regexp: '^refactor'
      order: 3
    - title: 'Other'
      order: 999

release:
  github:
    owner: ar4mirez
    name: samuel
  draft: false
  prerelease: auto
  name_template: "Samuel v{{.Version}}"
  header: |
    ## Samuel v{{.Version}}

    ### Installation

    **macOS/Linux (Homebrew):**
    ```bash
    brew tap ar4mirez/tap
    brew install samuel
    ```

    **macOS/Linux (curl):**
    ```bash
    curl -sSL https://raw.githubusercontent.com/ar4mirez/samuel/main/install.sh | sh
    ```

    **Direct download:**
    Download the appropriate binary for your platform below.

  footer: |

    ---

    **Full Changelog**: https://github.com/ar4mirez/samuel/compare/{{ .PreviousTag }}...{{ .Tag }}

homebrew_casks:
  - name: samuel
    binaries:
      - samuel
    repository:
      owner: ar4mirez
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/ar4mirez/samuel"
    description: "CLI for managing the Samuel (Artificial Intelligence Coding Framework)"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/samuel"]
          end

# Announce via webhook (optional)
# announce:
#   slack:
#     enabled: true
#     channel: '#releases'
